### ISSUE TITLE
Formalisation todo list

### ISSUE THREAD

**Issue by andy-morris** [anoma/juvix#239]
- [x] Add first-class usages (#99)
- [ ] Make sure subusaging is well-behaved
- [ ] Type safety proof
- [ ] Confluence of reduction
- [ ] Termination of reduction on well-typed terms

**Comment by cwgoes** [comment]
- [ ] Formalise self-types for induction over lambda-encoded data types
 (blocked on language reference explaining this much more clearly)
- [ ] Formalise linear logic types (low-priority for now)
- [ ] Formalise parameterisation over primitive types / primitive values (minor)

**Comment by cwgoes** [comment]
@andy-morris I was discussing a bit with someone and he mentioned that it might be nice to also check that evaluation-with-all-nonzero-usages-as-omega should be equivalent to evaluation with specific usages - that seems like it would be relatively easy to prove? Would be nice to isolate any potential mistakes in our usage accounting from actual computational behaviour.
