### ISSUE TITLE
Language reference updates

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#253]
Necessary for 1.0
- [ ] Update for first-class usages
- [ ] Update for sub-typing (ref https://github.com/cryptiumlabs/juvix/pull/375) incl. usages
- [ ] Details on Michelson backend & compilation of e.g. datatypes, pattern-matching
- [x] Basic schematic for arithmetic circuit backend compilation algorithm
- [x] Describe multi-backend targeting strategy (https://github.com/cryptiumlabs/juvix/issues/157)
- [ ] Compiler architecture diagrams
- [ ] Frontend language details (#273)
  - [ ] Basic syntax
  - [ ] Implicit arguments
  - [ ] Datatype definitions
  - [ ] Pattern matching & case expressions
  - [ ] Totality checking
  - [ ] Various pipelines for different backends (incl. visualisation)
  - [ ] Typeclasses
- [ ] Frontend => core transformation passes in detail
- [ ] Typechecking algorithm (nice example in [Agda paper](http://www.cse.chalmers.se/~ulfn/papers/thesis.pdf))
- [ ] Totality checker algorithm - ref https://github.com/cryptiumlabs/juvix/issues/33

Can be delayed to post-1.0:
- [ ] Details / examples on induction for lambda-encoded data types
- [ ] Full argument for interaction net correctness with context semantics
- [ ] Details on bespoke encoding pipeline (borrow abstract machine from GRIN?)
- [ ] Details on how usage information can be used to optimise abstract machine
- [ ] Details on plans for resource verification ([ref](https://github.com/cryptiumlabs/juvix/issues/45))
- [ ] Update constraint solving algorithm to deal correctly with dependent types
- [ ] Update language reference for updated constraint solving algorithm
- [ ] Add discrete derivation for `forall x . (x + 0) = x` using `Eq` / `Refl` / primitive Nat.
- [x] Details on compilation of optimal reduction to stack machines - https://github.com/cryptiumlabs/juvix/issues/296

**Comment by cwgoes** [comment]
Reconceptualise Juvix documentation and then assign people to write it, this is too out-of-date.
