### ISSUE TITLE
Update nockma backend output to match Anoma interface

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#3106]
## Current Situation

The nockma backend currently outputs a nockma function, i.e a cell with the following structure:

```
[code args context]
```

Where:

* `code` - is the code that's evaluated when the function is called
* `args` - is a placeholder for arguments to the function. The caller replaces this with the actual arguments before they call the function.
* `context` - some other data that's used by the function.

The nockma backend current stores the compiled functions from the module, information about closures, the anoma standard library and other things in the context:

https://github.com/anoma/juvix/blob/f1bb0e50d9864a4d16e23400d7f435dce6bfb397/src/Juvix/Compiler/Nockma/Translation/FromTree.hs#L162-L167

## New requirement from Anoma

Anoma requires the transaction function nock `context` to have the following structure:

```
[juvix-specific-data anoma-stdlib-placeholder]
``` 

where:
`juvix-specific-placeholder` is a `0` that will be replaced with the Anoma standard library when it is called by the Anoma.

i.e the whole structure of the nock function should be:

```
[code args juvix-specific-data anoma-stdlib-placeholder]
```

## TODO

- [x] Use [resource-machine.hoon](https://github.com/anoma/anoma/blob/a20b5e78380b4dcf554fda6f4c75758cc1b70063/hoon/resource-machine.hoon) instead of [anoma.hoon](https://github.com/anoma/anoma/blob/a20b5e78380b4dcf554fda6f4c75758cc1b70063/hoon/anoma.hoon) to compute nock indicies of stdlib functions (resource-machine.hoon contains anoma.hoon).
- [x] Change the [nockma closure structure](https://github.com/anoma/juvix/blob/f1bb0e50d9864a4d16e23400d7f435dce6bfb397/src/Juvix/Compiler/Nockma/Translation/FromTree.hs#L158) so the StandardLibrary is at the tail of the closure cell 
- [ ] Do not include the standard library nock code in the compiled output, just set the StandardLibrary slot to `nil`. (We will still use the standard library nock code in tests).

**Comment by paulcadman** [comment]
I'll split out

* Do not include the standard library nock code in the compiled output

into a separate issue because we don't need to do this immediately. Our compiler output is now compatible with the Anoma calling interface.
