### ISSUE TITLE
Milnesium release planning

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#693]
Target date: April 15th.

Frontend
- [x] S-expression pipeline refactor - https://github.com/heliaxdev/juvix/issues/671 (@mariari) (~ a few weeks)
- [ ] First version of proof UX - https://github.com/metastatedev/juvix/issues/518 (@cyberglot) (syntax) (ideally all the way through, maybe ~month)
- [ ] Add backend selection per-module - https://github.com/heliaxdev/juvix/issues/683 (@systemf-frank) (syntax) (tbd)
- [ ] Agree on ordering constraints, and alter pipeline accordingly (@mariari @andy-morris)
      Remember order from source (record it in the context somehow), require explicit mutual blocks
- [ ] Export lists in modules (@mariari) (syntax)
- [ ] Indent-sensitivity syntax changes - https://github.com/heliaxdev/juvix/issues/701 (@mariari)

Core
- [ ] Datatype & pattern matching integration - https://gist.github.com/thealmarty/2e58f3949d1ff2bac926a2313c7d6a75  (@thealmarty)
- [ ] Full context through core - https://github.com/heliaxdev/juvix/issues/531 (@andy-morris)
- [ ] Typechecker needs to annotate globals - https://github.com/metastatedev/juvix/issues/495 (@andy-morris)
- [x] Parameterisation clean-up - https://github.com/metastatedev/juvix/issues/506 (@systemf-frank)
- [ ] Pattern matching in terms - https://github.com/metastatedev/juvix/issues/536 (@andy-morris @thealmarty) (to be further investigated)
- [ ] First version of proof UX - https://github.com/metastatedev/juvix/issues/518 (@cyberglot) (typechecker, tactics)
- [ ] Add basic logic for multi-backend compilation architecture - https://github.com/heliaxdev/juvix/issues/157 (@systemf-frank)

Backends
- [ ] Full context through backends - https://github.com/heliaxdev/juvix/issues/531 (@mariari)
- [ ] Datatype & pattern matching compilation to Michelson (@mariari)
- [x] Add trivial dummy LLVM backend to test multi-backend architecture - #778 (@systemf-frank)

App
- [x] Clean up the pipeline usage pattern - https://github.com/heliaxdev/juvix/issues/692 (@systemf-frank)
- [ ] Basic REPL (if we have time, lower priority) (@systemf-frank @mariari)

Misc
- [x] Add a pretty-printer for terms so error messages are more legible (@andy-morris)
- [x] Pass error positions through from parser (@Acentelles)
- [ ] End-to-end semantic integration tests for Michelson (@Acentelles)
- [ ] Add Haddock documentation for Juvix
- [ ] Update the language reference / unify documentation (all)
- [ ] Think more about type theory (first-class usages, graded modalities, etc.) and start to formalise if we have time

**Comment by cwgoes** [comment]
Release since cut.
